### ISSUE TITLE
TypeError: JsonRpcProvider (Help)

### ISSUE THREAD

**Issue by monteago30** [austintgriffith/web2-to-web3-curriculum#4]
I am working on the Week 2, Day 1: Scripting and Smart Contracts and having an issue with executing "node providers.js" script.  I keep getting the following error: 

const provider = new ethers.providers.JsonRpcProvider(infuraUrl);
                                                                         ^

TypeError: Cannot read properties of undefined (reading 'JsonRpcProvider')
    at file:///Users/********/Documents/solidity-learning/ether-scripts/providers.js:10:39
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0

```
providers.js file:

import 'dotenv/config';
import { ethers } from 'ethers';

// const { JsonRpcProvider } = require("ethers");

const infuraUrl = `https://mainnet.infura.io/v3/${process.env.INFURA_KEY}`;

const provider = new ethers.providers.JsonRpcProvider(infuraUrl);
//const provider = new ethers.providers.InfuraProvider(network = 'homestead', process.env.INFURA_KEY);

console.log("Current block number", await provider.getBlockNumber());
```

**Comment by carletex** [comment]
Hey @monteago30 

Which version of ethers are you using? We used ethers v5 while recording the videos. Maybe you are using v6?

If that's the case, ethers change the access to providers, check: https://docs.ethers.org/v6/migrating/#migrate-providers

**Comment by monteago30** [comment]
Hi @carletex 
thank you that worked...change to the following and i was able to interact with the network:

const provider = new ethers.JsonRpcProvider(infuraUrl);

**Comment by carletex** [comment]
:fire: !! Glad to hear. Keep building! :rocket:
